### ISSUE TITLE
About search code

### ISSUE THREAD

**Issue by GongXinyuu** [meijieru/AtomNAS#1]
Hi, thanks for your great work! 
Do you plan to release the search code?

**Comment by meijieru** [comment]
It's already released. This repo contains code for both searching and retraining (if necessary)

**Comment by guvcolie** [comment]
It seems that you only show the script for training the final A B C model,
AtomNAS-A: bash scripts/run.sh apps/slimming/shrink/atomnas_a.yml
AtomNAS-B: bash scripts/run.sh apps/slimming/shrink/atomnas_b.yml
AtomNAS-C: bash scripts/run.sh apps/slimming/shrink/atomnas_c.yml
But if I wanna train the supernet, which script and config should I run?  Thank you!

**Comment by meijieru** [comment]
These configs conduct search & train in one pass.

**Comment by GongXinyuu** [comment]
Thank you for the clarification!
