### ISSUE TITLE
Doubt about the AtomNAS-C.

### ISSUE THREAD

**Issue by iFLYTEK-Embodied-Robotics-Team** [meijieru/AtomNAS#10]
@meijieru 
Hi, thanks for your great work! The first block of AtomNAS-C in the code only have single kernel size: 3 (first block:[1, 16, 1, 1, [3]]), but the Figure 5 in the paper show there have three kernel size(show as three difference color)，why? looking forward your reply!

**Comment by meijieru** [comment]
That block corresponds to the first homogeneous blue block, which is fixed.

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
@meijieru 
Thank you for your prompt reply. By the way, Could provid the MobileNetV2's pretrain model as your paper implement. Thank you!

**Comment by meijieru** [comment]
@zhangyuan1994511 Uploaded.

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
@meijieru 
Thank you very much, you are so nice!
