### ISSUE TITLE
Questions about the baseline models

### ISSUE THREAD

**Issue by colorjam** [meijieru/AtomNAS#6]
Hi, thank you for your interesting work. 
1. Why the FLOPs of MobileNetV2 your implementation (301M) is different from the original paper (300M) in Table 1?
2. Can you provide the pre-trained model?

**Comment by meijieru** [comment]
Sorry for the late reply.
1. It has 300.xM parameters, which is rounded to 301M.
1. We are organizing the code and a new version will be released soon, where the pre-trained model will be provided.
