### ISSUE TITLE
torch 1.3 breaks train.py

### ISSUE THREAD

**Issue by DameNianch** [meijieru/AtomNAS#7]
```
File "train.py", line 375, in run_one_epoch
data_iterator.data_queue.qsize(),
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'data_queue'
```
In torch.utils.data.DataLoader, different point is a _**data_queue**_
ver 1.2.0: data_queue
ver 1.3.0: _data_queue

**Comment by meijieru** [comment]
The udpated version in master branch has solved this problem.
