### ISSUE TITLE
Test AtomNas-a occur missing keys and size mismatch

### ISSUE THREAD

**Issue by andyhahaha** [meijieru/AtomNAS#9]
I use this command to test AtomNas-a.
FILE=$(realpath pretrained/atomnas-a) CHECKPOINT=ckpt  ATOMNAS_VAL=True bash scripts/run.sh apps/eval/eval_shrink.yml

Missing keys and size mismatch occur.

```
RuntimeError: Error(s) in loading state_dict for AllReduceDistributedDataParallel:
        Missing key(s) in state_dict: "module.features.5.ops.2.0.0.weight", "module.features.5.ops.2.0.1.weight", "module.features.5.ops.2.0.1.bias", "module.features.5.ops.2.0.1.running_mean", "module.features.5.ops.2.0.1.running_var", "module.features.5.ops.2.1.0.weight", "module.features.5.ops.2.1.1.weight", "module.features.5.ops.2.1.1.bias", "module.features.5.ops.2.1.1.running_mean", "module.features.5.ops.2.1.1.running_var", "module.features.5.ops.2.2.weight".
        size mismatch for module.features.4.ops.0.0.0.weight: copying a param with shape torch.Size([9, 24, 1, 1]) from checkpoint, the shape in current model is torch.Size([10, 24, 1, 1]).
        size mismatch for module.features.4.ops.0.0.1.weight: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([10]).
        size mismatch for module.features.4.ops.0.0.1.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([10]).
        size mismatch for module.features.4.ops.0.0.1.running_mean: copying a param with shape torch.Size([9]) from checkpoint,
the shape in current model is torch.Size([10]).
...
```

I can test AtomNas-b and AtomNas-c correctly, so I think the code is right.
Is there something wrong with AtomNas-a ckpt?

**Comment by meijieru** [comment]
We have updated the corresponding config file.
Sorry for the inconvenience.

**Comment by zhangyuan1994511** [comment]
@meijieru Hi, Author！I'm sorry to trouble you. My training process is interrupted and resume the training process, but I get  Missing keys errors. How to solve it? By the way, Do you meet the 'AssertionError: InvertedResidual.......' at 'prune.py' line 275 during the training process, I have been interrupted by this error, It's seem a bug, please check it.

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
@meijieru 
Hi, Author！I'm sorry to trouble you. My training process is interrupted and resume the training process, but I get Missing keys errors. How to solve it? By the way, Do you meet the 'AssertionError: InvertedResidual.......' at 'prune.py' line 275 during the training process? I have been interrupted by this error, It's seem a bug, please check it.

**Comment by meijieru** [comment]
> @meijieru
> Hi, Author！I'm sorry to trouble you. My training process is interrupted and resume the training process, but I get Missing keys errors. How to solve it? By the way, Do you meet the 'AssertionError: InvertedResidual.......' at 'prune.py' line 275 during the training process? I have been interrupted by this error, It's seem a bug, please check it.

Please provide more context and this seems to be another issue.

**Comment by zhangyuan1994511** [comment]
@meijieru 
Thank you for your reply! Here is the training log:
05/11 05:21:10 PM Epoch 72/350 Iter 2484/2503 train: loss: 3.4846, top1_error: 0.5786, top5_error: 0.3349
05/11 05:24:21 PM Epoch 72/350 bn_calibration: loss: 1.9954, top1_error: 0.4417, top5_error: 0.2236
05/11 05:25:49 PM Epoch 72/350 val: loss: 1.6668, top1_error: 0.3891, top5_error: 0.1700
WARNING:root:uncomment this for previous trained search_first model
WARNING:root:uncomment this for previous trained search_first model
WARNING:root:uncomment this for previous trained search_first model
05/11 05:25:49 PM Flops threshold: 0.001
05/11 05:25:49 PM Pruned model: {'input_channel': 16, 'last_channel': 1280, 'width_mult': 1.0, 'round_nearest': 8, 'active_fn': 'nn.ReLU', 'num_classes': 1000, 'inverted_residual_setting': [[16, 1, 1, [3], [16], False], [24, 1, 2, [3, 5, 7], [10, 12, 3], True], [24, 1, 1, [3], [3], True], [24, 1, 1, [3, 5], [4, 2], True], [24, 1, 1, [3, 5], [8, 1], True], [40, 1, 2, [3, 5, 7], [33, 33, 35], True], [40, 1, 1, [3, 5, 7], [12, 12, 7], True], [40, 1, 1, [3, 5], [7, 2], True], [40, 1, 1, [3, 5, 7], [11, 6, 1], True], [80, 1, 2, [3, 5, 7], [88, 79, 71], True], [80, 1, 1, [3, 5, 7], [14, 18, 30], True], [80, 1, 1, [3, 5, 7], [11, 4, 10], True], [80, 1, 1, [3, 5, 7], [16, 5, 6], True], [96, 1, 1, [3, 5, 7], [219, 89, 88], True], [96, 1, 1, [3, 5, 7], [16, 6, 7], True], [96, 1, 1, [3, 5, 7], [11, 5, 5], True], [96, 1, 1, [3, 5, 7], [17, 5, 1], True], [192, 1, 2, [3, 5, 7], [189, 144, 133], True], [192, 1, 1, [3, 5, 7], [18, 15, 91], True], [192, 1, 1, [3, 5, 7], [34, 14, 86], True], [192, 1, 1, [3, 5, 7], [77, 21, 53], True], [320, 1, 1, [3, 5, 7], [351, 214, 347], True]]}
05/11 05:25:49 PM Prune threshold: 0.001, flops pruned: 7928298.0, flops remain: 142568119.0
05/11 05:25:49 PM uncomment this for previous trained search_first model
05/11 05:25:50 PM Model Shrink to FLOPS: 149915767
05/11 05:25:50 PM Current model: {'input_channel': 16, 'last_channel': 1280, 'width_mult': 1.0, 'round_nearest': 8, 'active_fn': 'nn.ReLU', 'num_classes': 1000, 'inverted_residual_setting': [[16, 1, 1, [3], [16], False], [24, 1, 2, [3, 5, 7], [18, 18, 5], True], [24, 1, 1, [3, 7], [3, 3], True], [24, 1, 1, [3, 5], [4, 3], True], [24, 1, 1, [3, 5, 7], [9, 1, 2], True], [40, 1, 2, [3, 5, 7], [33, 33, 35], True], [40, 1, 1, [3, 5, 7], [12, 12, 7], True], [40, 1, 1, [3, 5], [7, 2], True], [40, 1, 1, [3, 5, 7], [11, 6, 1], True], [80, 1, 2, [3, 5, 7], [88, 79, 71], True], [80, 1, 1, [3, 5, 7], [14, 18, 30], True], [80, 1, 1, [3, 5, 7], [11, 4, 10], True], [80, 1, 1, [3, 5, 7], [16, 5, 6], True], [96, 1, 1, [3, 5, 7], [219, 89, 88], True], [96, 1, 1, [3, 5, 7], [16, 6, 7], True], [96, 1, 1, [3, 5, 7], [11, 5, 5], True], [96, 1, 1, [3, 5, 7], [17, 5, 1], True], [192, 1, 2, [3, 5, 7], [189, 144, 133], True], [192, 1, 1, [3, 5, 7], [18, 15, 91], True], [192, 1, 1, [3, 5, 7], [34, 14, 86], True], [192, 1, 1, [3, 5, 7], [77, 21, 53], True], [320, 1, 1, [3, 5, 7], [351, 214, 347], True]]}
05/11 05:25:50 PM New best validation top1 error: 0.3891
05/11 05:26:57 PM Epoch 73/350 Iter 81/2503 train: loss: 3.4398, top1_error: 0.5676, top5_error: 0.3241
05/11 05:28:12 PM Epoch 73/350 Iter 181/2503 train: loss: 3.4401, top1_error: 0.5734, top5_error: 0.3248
05/11 05:29:26 PM Epoch 73/350 Iter 281/2503 train: loss: 3.4582, top1_error: 0.5719, top5_error: 0.3282
05/11 05:30:44 PM Epoch 73/350 Iter 381/2503 train: loss: 3.4486, top1_error: 0.5733, top5_error: 0.3272
05/11 05:32:06 PM Epoch 73/350 Iter 481/2503 train: loss: 3.4571, top1_error: 0.5754, top5_error: 0.3320
05/11 05:33:25 PM Epoch 73/350 Iter 581/2503 train: loss: 3.4533, top1_error: 0.5741, top5_error: 0.3278
05/11 05:34:45 PM Epoch 73/350 Iter 681/2503 train: loss: 3.4558, top1_error: 0.5737, top5_error: 0.3286
05/11 05:36:06 PM Epoch 73/350 Iter 781/2503 train: loss: 3.4636, top1_error: 0.5766, top5_error: 0.3316
05/11 05:37:28 PM Epoch 73/350 Iter 881/2503 train: loss: 3.4676, top1_error: 0.5750, top5_error: 0.3307
05/11 05:38:49 PM Epoch 73/350 Iter 981/2503 train: loss: 3.4848, top1_error: 0.5783, top5_error: 0.3346
05/11 05:40:12 PM Epoch 73/350 Iter 1081/2503 train: loss: 3.4818, top1_error: 0.5787, top5_error: 0.3323
05/11 05:41:35 PM Epoch 73/350 Iter 1181/2503 train: loss: 3.4818, top1_error: 0.5785, top5_error: 0.3345
05/11 05:42:57 PM Epoch 73/350 Iter 1281/2503 train: loss: 3.4709, top1_error: 0.5795, top5_error: 0.3300
05/11 05:44:18 PM Epoch 73/350 Iter 1381/2503 train: loss: 3.4680, top1_error: 0.5768, top5_error: 0.3303
05/11 05:45:42 PM Epoch 73/350 Iter 1481/2503 train: loss: 3.4693, top1_error: 0.5780, top5_error: 0.3316
05/11 05:47:06 PM Epoch 73/350 Iter 1581/2503 train: loss: 3.4848, top1_error: 0.5814, top5_error: 0.3338
05/11 05:48:29 PM Epoch 73/350 Iter 1681/2503 train: loss: 3.4853, top1_error: 0.5784, top5_error: 0.3352
05/11 05:49:55 PM Epoch 73/350 Iter 1781/2503 train: loss: 3.4832, top1_error: 0.5784, top5_error: 0.3344
05/11 05:51:20 PM Epoch 73/350 Iter 1881/2503 train: loss: 3.4798, top1_error: 0.5773, top5_error: 0.3358
05/11 05:52:42 PM Epoch 73/350 Iter 1981/2503 train: loss: 3.4718, top1_error: 0.5774, top5_error: 0.3323
05/11 05:54:07 PM Epoch 73/350 Iter 2081/2503 train: loss: 3.4826, top1_error: 0.5775, top5_error: 0.3345
05/11 05:55:33 PM Epoch 73/350 Iter 2181/2503 train: loss: 3.5092, top1_error: 0.5821, top5_error: 0.3380
05/11 05:56:58 PM Epoch 73/350 Iter 2281/2503 train: loss: 3.5000, top1_error: 0.5823, top5_error: 0.3349
05/11 05:58:24 PM Epoch 73/350 Iter 2381/2503 train: loss: 3.4859, top1_error: 0.5814, top5_error: 0.3344
05/11 05:59:49 PM Epoch 73/350 Iter 2481/2503 train: loss: 3.4964, top1_error: 0.5793, top5_error: 0.3373
05/11 06:03:01 PM Epoch 73/350 bn_calibration: loss: 1.9819, top1_error: 0.4386, top5_error: 0.2221
05/11 06:04:30 PM Epoch 73/350 val: loss: 1.6638, top1_error: 0.3885, top5_error: 0.1693
WARNING:root:uncomment this for previous trained search_first model
WARNING:root:uncomment this for previous trained search_first model
WARNING:root:uncomment this for previous trained search_first model
05/11 06:04:30 PM Flops threshold: 0.001
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 480, in main
    train_val_test()
  File "train.py", line 389, in train_val_test
    infos, prune_threshold)
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/utils/distributed.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "train.py", line 119, in log_pruned_info
    prune.output_searched_network(model, infos, FLAGS.prune_params)))
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/utils/prune.py", line 275, in output_searched_network
    assert c == info[1], '{}, {}, {}, {}'.format(block, k, c, str(info))
AssertionError: InvertedResidual(16, 24, channels=[18, 18, 5], kernel_sizes=[3, 5, 7], expand=True, stride=2), 3, 18, ['features.3.ops.1.1.1.weight', 3, 3, 912576.0, 912576.0, 1.0]
bt-yuanzhang10-2c275f87-b797-prun-ptjob-worker-4cgz-1-4kpkf:112:112 [0] NCCL INFO Destroyed comm 0x7f2b74001aa0 rank 0
Traceback (most recent call last):
  File "/home/cv1/yuanzhang10/Software/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cv1/yuanzhang10/Software/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cv1/yuanzhang10/Software/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/cv1/yuanzhang10/Software/anaconda3/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/cv1/yuanzhang10/Software/anaconda3/bin/python', '-u', 'train.py', 'app:apps/slimming/shrink/atomnas_a.yml']' returned non-zero exit status 1.
./scripts/utils/remote_run.sh: line 13: pp:apps/slimming/shrink/atomnas_a.yml: No such file or directory
Traceback (most recent call last):
  File "train.py", line 484, in <module>
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 465, in main
Traceback (most recent call last):
  File "train.py", line 484, in <module>
    main()
  File "train.py", line 465, in main
    mc.setup_distributed(NUM_IMAGENET_TRAIN)
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/common.py", line 189, in setup_distributed
    mc.setup_distributed(NUM_IMAGENET_TRAIN)
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/common.py", line 189, in setup_distributed
    main()
  File "train.py", line 465, in main
    mc.setup_distributed(NUM_IMAGENET_TRAIN)
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/common.py", line 189, in setup_distributed
    udist.init_dist()
    udist.init_dist()
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/utils/distributed.py", line 30, in init_dist
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/utils/distributed.py", line 30, in init_dist
    udist.init_dist()
  File "/work/cv1/yuanzhang10/NAS/AtomNAS/utils/distributed.py", line 30, in init_dist
    assert rank % torch.cuda.device_count() == local_rank
AssertionError
    assert rank % torch.cuda.device_count() == local_rank
AssertionError
    assert rank % torch.cuda.device_count() == local_rank
AssertionError
Experiment dir : exp/atomnas_a/20200511-180943
05/11 06:09:47 PM Env var expand: ${DATA_LMDB} to /yrfs2/cv1/yuanzhang10/imagenet/lmdb
05/11 06:09:47 PM Env var expand: ${ARNOLD_OUTPUT}/atomnas_a to exp/atomnas_a
05/11 06:09:47 PM log_interval_detail: 2000
prune_params:
    method: network_slimming
    bn_prune_filter: expansion_only_skip_expand1
    rho: 0.00018
    epoch_free: 0
    epoch_warmup: 25
    scheduler: linear
    stepwise: True
    logging_verbose: False
model_shrink_delta_flops: 1000000.0
model_shrink_threshold: 0.001
dataset: imagenet1k_lmdb
data_transforms: imagenet1k_mnas_bicubic
data_loader: imagenet1k_basic
dataset_dir: /yrfs2/cv1/yuanzhang10/imagenet/lmdb
data_loader_workers: 16
image_size: 224
topk: [1, 5]
num_epochs: 350
optimizer: rmsprop
momentum: 0.9
alpha: 0.9
epsilon: 0.001
eps_inside_sqrt: True
weight_decay: 1e-05
weight_decay_method: mnas
base_lr: 0.016
base_total_batch: 64
per_gpu_batch_size: 128
lr_scheduler: exp_decaying
lr_stepwise: False
exp_decaying_lr_gamma: 0.97
exp_decay_epoch_interval: 2.4
label_smoothing: 0.1
moving_average_decay: 0.9999
moving_average_decay_adjust: True
moving_average_decay_base_batch: 1024
profiling: ['gpu']
log_interval: 100
pretrained: 
resume: 
test_only: False
random_seed: 1995
reset_parameters: True
reset_param_method: mnas
model: models.mobilenet_supernet
bn_calibration: True
bn_calibration_steps: 128
bn_calibration_per_gpu_batch_size: 256
use_distributed: True
allreduce_bn: False
log_dir: exp/atomnas_a/20200511-180943
model_kwparams:
    active_fn: nn.ReLU
    num_classes: 1000
    input_channel: 16
    last_channel: 1280
    width_mult: 1.0
    round_nearest: 8
    inverted_residual_setting: [[1, 16, 1, 1, [3]], [6, 24, 4, 2, [3, 5, 7]], [6, 40, 4, 2, [3, 5, 7]], [6, 80, 4, 2, [3, 5, 7]], [6, 96, 4, 1, [3, 5, 7]], [6, 192, 4, 2, [3, 5, 7]], [6, 320, 1, 1, [3, 5, 7]]]
    batch_norm_momentum: 0.01
    batch_norm_epsilon: 0.001
config_path: apps/slimming/shrink/atomnas_a.yml
batch_size: 512
_loader_batch_size: 128
_loader_batch_size_calib: 256
lr: 0.128
_steps_per_epoch: 2503
05/11 06:09:47 PM Set seed: 1995
05/11 06:09:47 PM uncomment this for previous trained search_first model
05/11 06:09:48 PM Init model by: mnas

**Comment by meijieru** [comment]
@zhangyuan1994511 Please open a new issue and have a clean format, thanks.

**Comment by iFLYTEK-Embodied-Robotics-Team** [comment]
OK, I will close it and open a new issue.
